### ISSUE TITLE
why hidden field also get persisted?

### ISSUE THREAD

**Issue by erikdemarco** [FThompson/FormPersistence.js#10]
why hidden field also get persisted?

**Comment by FThompson** [comment]
I didn't think of a use case for excluding hidden forms when I designed this library.

If you know the names of the hidden form inputs you want to exclude, you can use the `exclude` option.

What is your use case / reason for wanting this feature? I could add it to the library if this is a common need. I could also add generic `includeFilter`/`excludeFilter` options.

**Comment by salixh5** [comment]
I could image stuff like session IDs, nonces and the like being stored in hidden fields.

**Comment by FThompson** [comment]
> I could image stuff like session IDs, nonces and the like being stored in hidden fields.

Good point. I'm publishing a release now (2.0.6) with `includeFilter` and `excludeFilter` options to enable this functionality.

The following example excludes hidden fields:

```javascript
FormPersistence.persist(form, { excludeFilter: element => element.type === 'hidden' });
```

Alternatively, the following example includes all non-hidden fields:

```javascript
FormPersistence.persist(form, { includeFilter: element => element.type !== 'hidden' });
```

Note: These new filter options don't apply to any elements that you fill in custom `valueFunctions`. However, name filter options (`include`/`exclude`) do apply there before the `valueFunctions` are applied.
