### ISSUE TITLE
workiong demo?

### ISSUE THREAD

**Issue by markosjal** [FThompson/FormPersistence.js#2]
Is there no working demo anywhere? Not even a jsfiddle?

**Comment by FThompson** [comment]
I’ll add one later today.

In the meantime, you can see how I used this library in a project [here](https://github.com/dominion-randomizer/dominion-randomizer.github.io/blob/master/static/js/randomizer.js).

**Comment by FThompson** [comment]
You can see a working JSFiddle [here](https://jsfiddle.net/fthompson/xa62drsh/).

**Comment by markosjal** [comment]
I have no idea how that working demo "works" no form persistence on my page nor the jsfiddle you provided. You refresh the page window and the data is GONE.

**Comment by FThompson** [comment]
@markosjal Are you using Edge by chance? I only tested this library to work on Chrome, Firefox, and Safari. I just tried running the example in Edge and it indeed does not work in Edge.

**Comment by FThompson** [comment]
Seems that Edge does not support the full standard for FormData, causing FormPersistence to fail. See #3. I'll update this shortly.

**Comment by markosjal** [comment]
Running chrome on Ubuntu .Will check version

**Comment by FThompson** [comment]
I originally developed this in Chrome on Ubuntu so that's surprising to me.

Checked just now and it works for me with Chrome 71.0.3578.98 on Ubuntu 18.10, what versions are you using? Also let me know if any errors are being logged in the console please :)

Also, just double checking that you are pressing the Submit button before refreshing the page, correct? If not, you'll need to do so in order for the form to persist in the linked example.

**Comment by markosjal** [comment]
66.0.3359.181

**Comment by FThompson** [comment]
> 66.0.3359.181

If you update Chrome does the issue still occur? Is this Ubuntu 18.10 or another version?

Also please let me know if anything appears in the console as well as verify that you are pressing the Submit button before refreshing the page.

**Comment by FThompson** [comment]
Tested on Chrome 66.0.3359.0 on both Ubuntu 18.10 and Windows 10 and the example code works as expected.

**Comment by markosjal** [comment]
Maybe the problem is what i expect it to do?

**Comment by FThompson** [comment]
What do you expect it to do?

**Comment by markosjal** [comment]
A I understand it it should cause all partially filled form settings to be
retained through a page refresh

**Comment by FThompson** [comment]
The form inputs are only retained if you submit the form. The saved values are then whatever values were submitted.

**Comment by markosjal** [comment]
Then the post on stack exchange was not relevant to the question . thanks

**Comment by FThompson** [comment]
Do you mean this post? https://stackoverflow.com/a/54083081/1247781

The example linked in the repository shows a different use case than the one in this StackOverflow answer.

**Comment by FThompson** [comment]
@markosjal Per your feedback, I realize the `persist` function could work more in line with the goals expressed in the StackOverflow questions.

`FormPersistence#persist` now will retain data upon refresh and *clear* it upon save by default.

See updates to the repository :) I hope this helps!
