### ISSUE TITLE
Add option to exclude fields

### ISSUE THREAD

**Issue by crabnky** [FThompson/FormPersistence.js#7]
Hi,

Is there any chance to add option to exclude some fields and prevent them from being saved?

Thanks!

**Comment by FThompson** [comment]
Hi! Not at the moment but I considered this feature last week and I think I would like to implement it with a few options:
* `include` - Whitelist the data names. Only inputs with a name in this array will be persisted.
* `exclude` - Blacklist the data names. Only inputs without a name in this array will be persisted.
* `includeFilter` - Include filter function for data elements `cb(elem)`. Only inputs for which this function returns true will be persisted.
* `excludeFilter` - Exclude filter function for data elements `cb(elem)`. Only inputs for which this function returns false will be persisted.

Would these options suit your use case? Would you like additional/different options?

Thanks for the feedback!

**Comment by FThompson** [comment]
Added `include` and `exclude` name filters. I am skipping function-based filters for now because such filtering can be done within value functions if needed, but I am open to adding these at a later date.

**Comment by crabnky** [comment]
Wow! You are really fast :)
Thank you much! This fits my needs perfectly. :)
