### ISSUE TITLE
Babel 7 compile problems

### ISSUE THREAD

**Issue by Ninos** [FThompson/FormPersistence.js#8]
Hey there,

I have problems with babel 7, that following code snippet is not polyfilled for e.g. IE11:
`const FormPersistence = (() => {`

All other libs and own code are working fine. I think there's a problem that transform plugins for babel are not working for that code. I'm using encore (in webpack). Here's my setting & used plugins:
```
.configureBabel(function (babelConfig) {
    // add additional presets
    babelConfig.presets.push('@babel/preset-flow');

    // no plugins are added by default, but you can add some
    babelConfig.plugins.push('@babel/plugin-proposal-class-properties');
    babelConfig.plugins.push('@babel/plugin-proposal-function-bind');
    babelConfig.plugins.push('@babel/plugin-proposal-object-rest-spread');
    babelConfig.plugins.push('@babel/plugin-transform-arrow-functions');
    babelConfig.plugins.push('@babel/plugin-transform-block-scoping');
    babelConfig.plugins.push('@babel/plugin-transform-function-name');
    babelConfig.plugins.push('@babel/plugin-transform-modules-commonjs');
    babelConfig.plugins.push('@babel/plugin-transform-object-assign');
    babelConfig.plugins.push('@babel/plugin-transform-typeof-symbol');
})
```

`preset-env` is included in webpack-encore by default.

Can you please have a look and fix the syntax of your code?

**Comment by FThompson** [comment]
Hey, this issue would seem to be a result of a bug in Babel's transformer because that line is valid ES6, but I have pushed a new release containing a fix for this issue. Please let me know if problems persist.

**Comment by Ninos** [comment]
Yeah seems so, thank you very much for your feedback. I'll open a ticket for that +1. You commit solved my problem.

See:
https://github.com/babel/babel/issues/10322
